services:
  - type: web
    name: ai-video-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEEPSEEK_KEY
        sync: false
      - key: ANTHROPIC_KEY
        sync: false
      - key: FIREWORKS_KEY
        sync: false
      - key: GROQ_KEY
        sync: false
